language: node_js
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    # run coverage only in Node 10
    - node_js: 10
      script:
        - npm run test
        - npm run test:coverage
        - istanbul-coveralls
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
